PAUSED = false
IS_TOOL_MODE = false
BGI = false
DEBUG = DEBUG or {}
VARS = VARS or {}
DEBUG.SKIP_TUTO = DEBUG.SKIP_TUTO or getenv("DEBUG.SKIP_TUTO") == "true"
DEBUG.SKIP_STORY = DEBUG.SKIP_STORY or getenv("DEBUG.SKIP_STORY") == "true"
DEBUG.UPDATE_CONDITION = DEBUG.UPDATE_CONDITION or getenv("DEBUG.UPDATE_CONDITION") == "true"
